//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RejestOsob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostPerson
    {
        public int IdPerson { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public System.DateTime BDate { get; set; }
        public string Photo { get; set; }
        public string Describe { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> LostDate { get; set; }
        public string LostPlace { get; set; }
    
        public virtual Gender Gender1 { get; set; }
    }
}
